### ISSUE TITLE
Unable to properly start eagler 1.8.8 on ngrok and can't start 1.5.2 at all 

### ISSUE THREAD

**Issue by Blu3jay9** [wxnnvs/AutoEagler#15]
To start, I can get 1.8.8 running on localhost.
However I cannot run it via Ngrok, it then says my token is invalid and won't give me an address to join. 
And when I try to run 1.5.2 it gives me an IP and runs on localhost but I can never get a connection via the eagler 1.5.2 client.

**Comment by STPv22** [comment]
are you the dude that posted that long asf reddit post?

**Comment by STPv22** [comment]
ws://localhost:<port> ?
@wxnnvs knows alot.

**Comment by wxnnvs** [comment]
Make sure your ngrok token is right.
Due to some updates in their service, it might be possible that ngrok sometimes breaks, but i update it fairly soon after.

To join localhost servers, please use an offline download and join on ws://localhost (or ws://127.0.0.1:8081)

**Comment by wxnnvs** [comment]
I'll check in an hour or so to see if something is broken

**Comment by wxnnvs** [comment]
I got busy, checking soon

**Comment by wxnnvs** [comment]
@Blu3jay9 1.5 and 1.3 fixed in latest commit
im checking for 1.8 rk

**Comment by wxnnvs** [comment]
![image](https://github.com/wxnnvs/AutoEagler/assets/136503688/f08a9be0-ef83-4597-b26c-b05dec2d0f8e)
1.8 works just fine

**Comment by Blu3jay9** [comment]
Thanks mate

**Comment by Blu3jay9** [comment]
Still having some issues
I'll see what I can come up with
it's most likely on my end though, tryna figure it out.

**Comment by Blu3jay9** [comment]
Can you do anything with these? I still can't get 1.5.2 to work at all, and 1.8.8 still only works on ws://localhost:
[1.8.8 log](https://github.com/wxnnvs/AutoEagler/files/14470960/2024-03-02_16-22-38.log.txt)
[1.5.2 log](https://github.com/wxnnvs/AutoEagler/files/14470968/2024-03-02_16-36-22.log.txt)

**Comment by Blu3jay9** [comment]
Also, is there any way to change the IP from the "****-****-****-ngrok.***" to one of the domains I own? 

I still have no idea how the servers work, and need a lot of help.

**Comment by wxnnvs** [comment]
It seems like you are still on an older version of autoeagler as it downloads from git.eaglercraft.online

**Comment by Blu3jay9** [comment]
I was using the latest release
lemme try again

**Comment by Blu3jay9** [comment]
Still having the same issues with the latest version, which is what I had installed

**Comment by wxnnvs** [comment]
Damn 
I dont know what the problem is here as everything works fine on my side
